Add Yunmin Song Info
awesome-devblog/awesome-devblog pull request #600
Opened 2021-12-18 19:23 UTC by SongYunMin

* 송윤민 블로그 추가 부탁드립니다!

2021-12-19 02:13 UTC, sarojaba requested changes
불필요한 파일들이 포함되어 있습니다.
이름순으로 위치해 주시기 바랍니다.

2021-12-19 17:37 UTC, SongYunMin commented
피드백 수정하였습니다..!

2021-12-20 01:40 UTC, sarojaba requested changes
자동 수집되어 포스팅이 노출되기 원하시면 RSS 도 추가부탁 드립니다.

2021-12-20 18:58 UTC, SongYunMin commented
피드백 감사합니다! 반영했습니다! :)

2021-12-20 23:07 UTC, sarojaba approved these changes

2021-12-20 23:07 UTC, merged

2021-12-20 23:08 UTC, sarojaba commented
정말 감사합니다!