강경석 블로그 추가
awesome-devblog/awesome-devblog pull request #631
Opened 2022-02-16 07:08 UTC by gyeongseokKang

강경석(핸디) 블로그 추가 부탁드립니다.

2022-02-16 08:13 UTC, gyewan90 requested changes

2022-02-16 08:13 UTC, gyewan90 commented on db.yml
> +  description: 편리함을 추구하는 개발자의 지식 블로그
rss 도 추가 부탁드립니다 😃

2022-02-16 08:23 UTC, gyeongseokKang commented on db.yml
> +  description: 편리함을 추구하는 개발자의 지식 블로그
제가 rss를 잘 몰라서 그런데요. 
지금 저 블로그가 개발에 관한 내용만 있는게 아니고 다른 카테고리도 있습니다.
해서 https://all-dev-kang.tistory.com/rss 를 보니 모든 카테고리에 대한 정보가 나와 추가하지 않았습니다.
혹시 rss를 추가한다면 내부적으로 블로그에 적은 url만 해당하는 글만 올리는가 가능한가요?

2022-02-16 09:03 UTC, sarojaba commented on db.yml
> +  description: 편리함을 추구하는 개발자의 지식 블로그
티스토리는 일부분에 대한 RSS 기능을 제공하지 않아서요. 블로그 주소와 RSS를 다른분들처럼 전체로 해주세요. 수집시 카테고리에 기반해서 필터링하겠습니다.

2022-02-16 09:17 UTC, gyeongseokKang commented on db.yml
> +  description: 편리함을 추구하는 개발자의 지식 블로그
블로그 주소와 RSS 수정했습니다.

감사합니다.

2022-02-17 11:01 UTC, gyewan90 requested changes
ide 설정 때문이신지 single quotes 가 double quotes 로 다 바뀌어버렸네요 😢  
원복 부탁드립니다...!

2022-02-18 06:07 UTC, merged

2022-02-18 06:08 UTC, gyewan90 commented
감사합니다 😃