AB180 기술 블로그 추가
awesome-devblog/awesome-devblog pull request #642
Opened 2022-04-20 02:21 UTC by toughrogrammer

안녕하세요. AB180 정주홍입니다.
저희 기술 블로그 추가 요청 드립니다.

2022-04-20 16:34 UTC, sarojaba requested changes
RSS에 Sitemap이 적혀있네요.
확인 부탁드립니다.

2022-07-04 10:56 UTC, toughrogrammer commented
@sarojaba 
안녕하세요. 오랜만에 다시 PR 업데이트 했습니다. 두 가지 변경 사항이 있습니다.

1. rss 정상화: 저번에 요청 드릴 때는 rss를 sitemap으로 추가했었는데요. 저희가 notion을 static site로 hosting 하기 위해 oopy라는 서비스를 쓰고 있는데, 여기서 rss를 지원하지 않아서 어쩔 수 없이 sitemap을 추가한 것이었습니다. rss를 따로 만들어야 하는 것은 여전해서 github을 통해 serving 할 rss로 업데이트 했습니다.
2. 중복 제거: 알고보니 이미 `에이비일팔공` 이라는 이름으로 추가가 되어 있었습니다. 그래서 원래의 `에이비일팔공` 아래에 rss와 description을 추가하도록 변경했습니다.

2022-07-04 13:32 UTC, sarojaba approved these changes
RSS 포맷은 맞는데, 블로그의 최신글과 매치가 안되네요.

2022-07-04 13:34 UTC, merged

2022-07-04 13:34 UTC, sarojaba commented
감사합니다.

2022-07-05 01:13 UTC, toughrogrammer commented
rss 업데이트는 곧 할 예정입니다! 감사합니다.