add techblog twjh_awesomedevblog
awesome-devblog/awesome-devblog pull request #676
Opened 2022-09-12 09:11 UTC by JangHyun1994

add techblog twjh_awesomedevblog

branch: twjh_awesomedevblog

2022-09-12 15:08 UTC, sarojaba requested changes
description 필드가 두개들어갔네요.

2022-09-13 06:51 UTC, JangHyun1994 commented
@sarojaba  제가 깃허브에 익숙하지 않은 학생이라, 우려가 돼 코멘트 남깁니다. 
description 오기입 수정했습니다. 정상적으로 처리된 건지 잘 모르겠네요. 감사합니다.

2022-09-13 07:23 UTC, sarojaba approved these changes

2022-09-13 07:23 UTC, merged

2022-09-13 07:25 UTC, sarojaba commented
@JangHyun1994
저도 깃헙 잘 다루지 못해서 ㅎㅎ
빠른 수정 감사드립니다.