이창희 블로그 추가
awesome-devblog/awesome-devblog pull request #716
Opened 2022-12-15 05:45 UTC by Junnyjun

# 백엔드 개발자입니다.
[Blog](https://junny-land.gitbook.io/til/)
[github](https://github.com/Junnyjun)

CS 및 JAVA,KOTLIN에 대해 주로 다룹니다.

2022-12-15 06:53 UTC, gyewan90 commented on db.yml
> +  blog: https://www.junnyland.com/til/
RSS 추가 부탁드려요! 그래야 수집이 되는 구조라서요.. 😅

2022-12-15 06:54 UTC, gyewan90 requested changes

2022-12-15 06:54 UTC, gyewan90 commented on db.yml
> +  blog: https://www.junnyland.com/til/
RSS도 추가 부탁드려요! 그래야 글이 수집되는 구조여서요.. 😅

2022-12-15 06:54 UTC, gyewan90 commented on db.yml
> +  description:
description도 간단하게나마 부탁드립니다~!

2022-12-15 07:16 UTC, Junnyjun commented on db.yml
> +  blog: https://www.junnyland.com/til/
사이트맵 추가했습니다!

2022-12-15 07:16 UTC, Junnyjun commented on db.yml
> +  description:
설명도 추가했습니다!

2022-12-16 17:37 UTC, sarojaba commented on db.yml
> +  blog: https://www.junnyland.com/til/
사이트맵 말고 RSS로 등록 부탁드립니다.

2022-12-21 05:34 UTC, sarojaba commented on db.yml
> +  rss: http://feed43.com/2520711468561642.xml
RSS 접근이 안됩니다. 확인 부탁드립니다.

2023-07-31 13:34 UTC, sarojaba commented
너무 오래되어 닫겠습니다.

2023-07-31 13:34 UTC, closed without merging