김종진 블로그 추가
awesome-devblog/awesome-devblog pull request #729
Opened 2023-02-03 14:53 UTC by nasir17git

안녕하세요. 블로그 추가 요청드립니다~

2023-02-03 19:08 UTC, sarojaba requested changes
RSS 추가 부탁드립니다.

2023-02-05 07:42 UTC, nasir17git commented
rss 링크 추가했습니다.

2023-02-05 13:09 UTC, sarojaba approved these changes

2023-02-05 13:09 UTC, merged

2023-02-05 13:10 UTC, sarojaba commented
감사합니다.