Jihoon Ahn 블로그 추가
awesome-devblog/awesome-devblog pull request #759
Opened 2023-05-02 14:18 UTC by Jihoonahn

Jihoonahn blog 추가 부탁드립니다.

2023-05-02 22:34 UTC, sarojaba reviewed
혹시 가능하면 한글 이름으로 해주시면 안될까요?

2023-05-03 05:00 UTC, Jihoonahn commented
넵, 요청 대로 다시 변경했습니다.

2023-05-03 09:37 UTC, sarojaba requested changes
앗... 이름순으로 정렬 부탁드립니다;;

2023-05-03 10:12 UTC, Jihoonahn commented
요청에 따라 이름순으로 다시 정렬했습니다.

2023-05-03 10:18 UTC, sarojaba approved these changes

2023-05-03 10:18 UTC, merged

2023-05-03 10:18 UTC, sarojaba commented
감사합니다!