구성우 블로그 추가
awesome-devblog/awesome-devblog pull request #806
Opened 2023-10-19 03:00 UTC by sungwookoo

구성우 블로그 추가 부탁드립니다 ^^

2023-10-20 03:19 UTC, sarojaba requested changes
마지막 라인의 개행이 삭제되었네요.
정확히 변경이 필요한 부분만 업데이트 부탁드립니다. ^^

2023-10-23 02:11 UTC, sungwookoo commented
> 마지막 라인의 개행이 삭제되었네요. 정확히 변경이 필요한 부분만 업데이트 부탁드립니다. ^^

업데이트 했습니다. 감사합니다 ^^

2023-10-23 03:40 UTC, sarojaba approved these changes

2023-10-23 03:41 UTC, merged

2023-10-23 03:41 UTC, sarojaba commented
감사합니다.