송규빈 블로그 추가
awesome-devblog/awesome-devblog pull request #852
Opened 2024-06-18 14:53 UTC by Songgyubin

송규빈 블로그 추가 요청드립니다.
감사합니다.

2024-06-18 21:24 UTC, sarojaba requested changes
이름순으로 정렬 부탁드립니다.

2024-06-19 02:49 UTC, Songgyubin commented
@sarojaba  수정하였습니다.

2024-06-19 02:55 UTC, sarojaba requested changes
마지막 줄 개행만 추가해주시면 될것 같습니다. 딱 본인 부분만 수정되도록요.

2024-06-19 03:03 UTC, Songgyubin commented
@sarojaba 네 수정하였습니다.

2024-06-19 04:43 UTC, sarojaba approved these changes

2024-06-19 04:43 UTC, merged

2024-06-19 04:43 UTC, sarojaba commented
감사합니다.